version: '3.8'

services:
  metabase:
    image: metabase/metabase:latest
    container_name: metabase
    ports:
      - '3002:3000'
    environment:
      MB_DB_FILE: /metabase-data/metabase.db
    volumes:
      - ./metabase-data:/metabase-data
#    networks:
#      - app_net
#    deploy:
#      resources:
#        limits:
#          memory: 1GB
    network_mode: "host"



#networks:
#  app_net:
#    external: true
#    name: app_net
#    driver: bridge
